# Generated by Django 5.2.1 on 2025-09-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='標題')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='圖片')),
                ('link', models.URLField(blank=True, null=True, verbose_name='連結')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
            ],
            options={
                'verbose_name': '首頁 Banner',
                'verbose_name_plural': '首頁 Banner',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='問題')),
                ('answer', models.TextField(verbose_name='答案')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '常見問題',
                'verbose_name_plural': '常見問題',
                'ordering': ['order'],
            },
        ),
    ]
