# Generated by Django 5.2.1 on 2025-06-15 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, verbose_name='英文分類名稱')),
                ('name_zh_tw', models.CharField(max_length=100, verbose_name='繁體分類名稱')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': '行程分類',
                'verbose_name_plural': '行程分類（複數）',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200, verbose_name='英文標題')),
                ('desc_en', models.TextField(blank=True, verbose_name='英文說明')),
                ('title_zh_tw', models.CharField(max_length=200, verbose_name='繁體標題')),
                ('desc_zh_tw', models.TextField(blank=True, verbose_name='繁體說明')),
                ('duration_days', models.IntegerField(default=1, verbose_name='行程天數')),
                ('departure_city', models.CharField(max_length=100, verbose_name='出發城市')),
                ('departure_time', models.TimeField(verbose_name='出發時間')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='價格')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tours/', verbose_name='主圖')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='tours.tourcategory', verbose_name='所屬分類')),
            ],
            options={
                'verbose_name': '行程',
                'verbose_name_plural': '行程列表',
            },
        ),
    ]
