# Generated by Django 5.2.1 on 2025-09-29 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartureRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='出發地區')),
            ],
            options={
                'verbose_name': '出發地區',
                'verbose_name_plural': '出發地區',
            },
        ),
        migrations.CreateModel(
            name='DepartureCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='出發城市')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='tours.departureregion', verbose_name='所屬地區')),
            ],
            options={
                'verbose_name': '出發城市',
                'verbose_name_plural': '出發城市',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='未命名行程', max_length=200, verbose_name='行程標題')),
                ('description', models.TextField(blank=True, null=True, verbose_name='行程描述')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='價格')),
                ('departure_date', models.DateField(blank=True, null=True, verbose_name='出發日期')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='瀏覽次數')),
                ('departure_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours', to='tours.departurecity', verbose_name='出發城市')),
            ],
            options={
                'verbose_name': '行程',
                'verbose_name_plural': '行程',
            },
        ),
    ]
