# Generated by Django 5.2.1 on 2025-07-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
