# Generated by Django 5.2.1 on 2025-08-21 19:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('tours', '0002_tour_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('b2c', 'B2C（官網/消費者）'), ('b2b', 'B2B（同業/代理）'), ('mkt', '行銷官網'), ('app', '行動端/小程式')], db_index=True, default='b2c', max_length=8)),
                ('hero_title', models.CharField(blank=True, default='', max_length=200)),
                ('hero_subtitle', models.CharField(blank=True, default='', max_length=300)),
                ('hero_bg_image', models.URLField(blank=True, default='')),
                ('show_breadcrumbs', models.BooleanField(default=True)),
                ('seo_title', models.CharField(blank=True, default='', max_length=200)),
                ('seo_description', models.CharField(blank=True, default='', max_length=300)),
                ('seo_keywords', models.CharField(blank=True, default='', max_length=300)),
                ('show_orders_widget', models.BooleanField(default=True)),
                ('show_points_widget', models.BooleanField(default=True)),
                ('show_profile_widget', models.BooleanField(default=True)),
                ('show_coupons_widget', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_configs', to='sites.site')),
            ],
            options={
                'ordering': ['site_id', 'channel'],
                'unique_together': {('site', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, default='', max_length=200)),
                ('slug', models.SlugField(blank=True, default='', max_length=60)),
                ('layout', models.CharField(choices=[('grid', '格線'), ('carousel', '橫向滑動'), ('list', '清單')], default='grid', max_length=16)),
                ('columns', models.PositiveIntegerField(default=3)),
                ('show_divider', models.CharField(choices=[('none', '無'), ('line', '水平線'), ('spacer', '空白間距')], default='line', max_length=10)),
                ('max_items', models.PositiveIntegerField(default=6)),
                ('more_label', models.CharField(blank=True, default='', max_length=40)),
                ('more_url', models.CharField(blank=True, default='', max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='tours.homeconfig')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SectionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, default='', max_length=200)),
                ('image_url', models.URLField(blank=True, default='')),
                ('price_label', models.CharField(blank=True, default='', max_length=40)),
                ('tag', models.CharField(blank=True, default='', max_length=30)),
                ('link_url', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='tours.section')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='Tour',
        ),
        migrations.DeleteModel(
            name='TourCategory',
        ),
    ]
