# Generated by Django 5.2.5 on 2025-09-08 16:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_tourcategory_tour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='home',
        ),
        migrations.RemoveField(
            model_name='sectioncard',
            name='section',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['-updated_at', '-id']},
        ),
        migrations.RemoveField(
            model_name='tour',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='image_url',
        ),
        migrations.AddField(
            model_name='tour',
            name='cabin_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tour',
            name='cover_image',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tour',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tour',
            name='desc',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tour',
            name='embark_port',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tour',
            name='en_translated',
            field=models.BooleanField(default=False, help_text='英文已完成'),
        ),
        migrations.AddField(
            model_name='tour',
            name='faq',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tour',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='meeting_point',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tour',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='sail_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_type',
            field=models.CharField(choices=[('bus_tour', '巴士團'), ('cruise_tour', '郵輪團')], db_index=True, default='bus_tour', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='zh_Hans_synced',
            field=models.BooleanField(default=True, help_text='簡體與繁體自動同步（未手改）'),
        ),
        migrations.AddField(
            model_name='tour',
            name='zh_Hant_translated',
            field=models.BooleanField(default=False, help_text='繁體已完成'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.DeleteModel(
            name='HomeConfig',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='SectionCard',
        ),
        migrations.DeleteModel(
            name='TourCategory',
        ),
    ]
