# Generated by Django 5.2.6 on 2025-09-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_remove_section_home_remove_sectioncard_section_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={},
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='sail_date',
            new_name='departure_date',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='cabin_type',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='embark_port',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='faq',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='meeting_point',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='pickup_time',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='price',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='zh_Hant_translated',
        ),
        migrations.AddField(
            model_name='tour',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='en_translated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tour',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_type',
            field=models.CharField(choices=[('usa', '美國團'), ('bus', '巴士團'), ('day', '一日遊')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tour',
            name='zh_Hans_synced',
            field=models.BooleanField(default=False),
        ),
    ]
