# Generated by Django 5.2.6 on 2025-09-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_alter_tour_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='tours/'),
        ),
    ]
