# Generated by Django 5.2.6 on 2025-09-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_tour_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='行程簡介'),
        ),
        migrations.AddField(
            model_name='tour',
            name='popularity',
            field=models.IntegerField(default=0, verbose_name='熱門排序'),
        ),
        migrations.AddField(
            model_name='tour',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='售價'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='tours/', verbose_name='封面圖'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='departure_date',
            field=models.DateField(blank=True, null=True, verbose_name='出發日期'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='en_translated',
            field=models.BooleanField(default=False, verbose_name='英文同步'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='上架'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(max_length=200, verbose_name='行程名稱'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_type',
            field=models.CharField(choices=[('usa', '美國團'), ('bus', '巴士團'), ('day', '一日遊'), ('cruise', '郵輪'), ('asia', '亞洲團'), ('canada', '加拿大')], max_length=20, verbose_name='行程類型'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='zh_Hans_synced',
            field=models.BooleanField(default=False, verbose_name='簡中同步'),
        ),
    ]
