# Generated by Django 5.2.6 on 2025-09-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_tour_description_tour_popularity_tour_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='標題')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='圖片')),
                ('link', models.URLField(blank=True, verbose_name='連結')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='顯示')),
            ],
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['-updated_at', '-id']},
        ),
    ]
