# Generated by Django 5.2.6 on 2025-09-21 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_banner_alter_tour_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartureCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_zh_hant', models.CharField(blank=True, max_length=100, null=True, verbose_name='城市名稱 (繁體)')),
                ('name_zh_hans', models.CharField(blank=True, max_length=100, null=True, verbose_name='城市名稱 (簡體)')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='城市名稱 (英文)')),
            ],
        ),
        migrations.CreateModel(
            name='DepartureRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_zh_hant', models.CharField(blank=True, max_length=100, null=True, verbose_name='地區名稱 (繁體)')),
                ('name_zh_hans', models.CharField(blank=True, max_length=100, null=True, verbose_name='地區名稱 (簡體)')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='地區名稱 (英文)')),
            ],
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={},
        ),
        migrations.RemoveField(
            model_name='tour',
            name='city',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='en_translated',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='popularity',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='price',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='title',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='tour_type',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='zh_Hans_synced',
        ),
        migrations.AddField(
            model_name='tour',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='描述 (英文)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='description_zh_hans',
            field=models.TextField(blank=True, null=True, verbose_name='描述 (簡體)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='description_zh_hant',
            field=models.TextField(blank=True, null=True, verbose_name='描述 (繁體)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='標題 (英文)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='title_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='標題 (簡體)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='title_zh_hant',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='標題 (繁體)'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否啟用'),
        ),
        migrations.AddField(
            model_name='tour',
            name='departure_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tours.departurecity'),
        ),
        migrations.AddField(
            model_name='departurecity',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='tours.departureregion'),
        ),
        migrations.AddField(
            model_name='tour',
            name='departure_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tours.departureregion'),
        ),
    ]
