# Generated by Django 5.2.6 on 2025-09-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_tour_price_alter_departurecity_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departurecity',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='城市名稱 (英文)'),
        ),
        migrations.AlterField(
            model_name='departurecity',
            name='name_zh_hans',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='城市名稱 (簡體)'),
        ),
        migrations.AlterField(
            model_name='departurecity',
            name='name_zh_hant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='城市名稱 (繁體)'),
        ),
        migrations.AlterField(
            model_name='departureregion',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='地區名稱 (英文)'),
        ),
        migrations.AlterField(
            model_name='departureregion',
            name='name_zh_hans',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='地區名稱 (簡體)'),
        ),
        migrations.AlterField(
            model_name='departureregion',
            name='name_zh_hant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='地區名稱 (繁體)'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='描述 (英文)'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description_zh_hans',
            field=models.TextField(blank=True, null=True, verbose_name='描述 (簡體)'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description_zh_hant',
            field=models.TextField(blank=True, null=True, verbose_name='描述 (繁體)'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='標題 (英文)'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title_zh_hans',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='標題 (簡體)'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title_zh_hant',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='標題 (繁體)'),
        ),
    ]
