# Generated by Django 5.2.6 on 2025-09-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_alter_departurecity_name_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='標題')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='圖片')),
                ('link', models.URLField(blank=True, null=True, verbose_name='連結')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
            ],
            options={
                'verbose_name': '首頁 Banner',
                'verbose_name_plural': '首頁 Banners',
                'ordering': ['order'],
            },
        ),
    ]
