# Generated by Django 5.2.6 on 2025-09-20 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='中文名稱')),
                ('name_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='英文名稱')),
            ],
            options={
                'verbose_name': '出發城市',
                'verbose_name_plural': '出發城市',
            },
        ),
        migrations.CreateModel(
            name='CruiseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='中文名稱')),
                ('name_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='英文名稱')),
            ],
            options={
                'verbose_name': '郵輪公司',
                'verbose_name_plural': '郵輪公司',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='中文名稱')),
                ('name_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='英文名稱')),
            ],
            options={
                'verbose_name': '出發地區',
                'verbose_name_plural': '出發地區',
            },
        ),
        migrations.CreateModel(
            name='CruiseShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='中文名稱')),
                ('name_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='英文名稱')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ships', to='cruise.cruiseline', verbose_name='所屬公司')),
            ],
            options={
                'verbose_name': '郵輪船隻',
                'verbose_name_plural': '郵輪船隻',
            },
        ),
        migrations.CreateModel(
            name='CruiseTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='行程標題')),
                ('depart_date', models.DateField(verbose_name='出發日期')),
                ('duration_days', models.PositiveIntegerField(verbose_name='天數')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='價格')),
                ('promotion', models.CharField(blank=True, max_length=200, null=True, verbose_name='優惠說明')),
                ('chinese_guide', models.BooleanField(default=False, verbose_name='中文導遊')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cruise.city', verbose_name='出發城市')),
                ('cruise_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cruise.cruiseline', verbose_name='郵輪公司')),
                ('cruise_ship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cruise.cruiseship', verbose_name='郵輪船隻')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cruise.region', verbose_name='出發地區')),
            ],
            options={
                'verbose_name': '郵輪行程',
                'verbose_name_plural': '郵輪行程',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='cruise.region', verbose_name='出發城市所屬地區'),
        ),
    ]
