# Generated by Django 5.2.6 on 2025-09-20 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruise', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cruiseline',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cruiseship',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cruisetour',
            options={},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={},
        ),
        migrations.RemoveField(
            model_name='city',
            name='name_en',
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, verbose_name='城市名稱'),
        ),
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cruise.region', verbose_name='所屬區域'),
        ),
        migrations.AlterField(
            model_name='cruiseline',
            name='name',
            field=models.CharField(max_length=100, verbose_name='航線名稱'),
        ),
        migrations.AlterField(
            model_name='cruiseline',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='英文名稱'),
        ),
        migrations.AlterField(
            model_name='cruiseship',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cruise.cruiseline', verbose_name='航線'),
        ),
        migrations.AlterField(
            model_name='cruiseship',
            name='name',
            field=models.CharField(max_length=100, verbose_name='郵輪名稱'),
        ),
        migrations.AlterField(
            model_name='cruiseship',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='英文名稱'),
        ),
        migrations.AlterField(
            model_name='cruisetour',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cruise.city', verbose_name='出發城市'),
        ),
        migrations.AlterField(
            model_name='cruisetour',
            name='cruise_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cruise.cruiseline', verbose_name='航線公司'),
        ),
        migrations.AlterField(
            model_name='cruisetour',
            name='cruise_ship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cruise.cruiseship', verbose_name='搭乘郵輪'),
        ),
        migrations.AlterField(
            model_name='cruisetour',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='售價'),
        ),
        migrations.AlterField(
            model_name='cruisetour',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cruise.region', verbose_name='出航地區'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=100, verbose_name='區域名稱'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='英文名稱'),
        ),
    ]
