# Generated by Django 5.2.1 on 2025-09-20 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruise', '0002_alter_city_options_alter_cruiseline_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cruise.region'),
        ),
        migrations.AlterField(
            model_name='cruiseline',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cruiseline',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cruiseship',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cruise.cruiseline'),
        ),
        migrations.AlterField(
            model_name='cruiseship',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cruiseship',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cruisetour',
            name='chinese_guide',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cruisetour',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cruise.city'),
        ),
        migrations.AlterField(
            model_name='cruisetour',
            name='cruise_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cruise.cruiseline'),
        ),
        migrations.AlterField(
            model_name='cruisetour',
            name='cruise_ship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cruise.cruiseship'),
        ),
        migrations.AlterField(
            model_name='cruisetour',
            name='depart_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cruisetour',
            name='duration_days',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='cruisetour',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cruisetour',
            name='promotion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cruisetour',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cruise.region'),
        ),
        migrations.AlterField(
            model_name='cruisetour',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='region',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
