# Generated by Django 5.2.1 on 2025-09-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruise', '0003_city_name_en_alter_city_name_alter_city_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruisetour',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
