# Generated by Django 5.2.6 on 2025-09-21 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruise', '0004_cruisetour_title_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cruisetour',
            name='city',
        ),
        migrations.RemoveField(
            model_name='cruisetour',
            name='cruise_line',
        ),
        migrations.RemoveField(
            model_name='cruiseship',
            name='line',
        ),
        migrations.RemoveField(
            model_name='cruisetour',
            name='cruise_ship',
        ),
        migrations.RemoveField(
            model_name='cruisetour',
            name='chinese_guide',
        ),
        migrations.RemoveField(
            model_name='cruisetour',
            name='depart_date',
        ),
        migrations.RemoveField(
            model_name='cruisetour',
            name='duration_days',
        ),
        migrations.RemoveField(
            model_name='cruisetour',
            name='promotion',
        ),
        migrations.RemoveField(
            model_name='cruisetour',
            name='region',
        ),
        migrations.RemoveField(
            model_name='cruisetour',
            name='title',
        ),
        migrations.RemoveField(
            model_name='region',
            name='name',
        ),
        migrations.AddField(
            model_name='cruisetour',
            name='departure_date',
            field=models.DateField(blank=True, null=True, verbose_name='出發日期'),
        ),
        migrations.AddField(
            model_name='cruisetour',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='描述 (英文)'),
        ),
        migrations.AddField(
            model_name='cruisetour',
            name='description_zh_hans',
            field=models.TextField(blank=True, null=True, verbose_name='描述 (簡體)'),
        ),
        migrations.AddField(
            model_name='cruisetour',
            name='description_zh_hant',
            field=models.TextField(blank=True, null=True, verbose_name='描述 (繁體)'),
        ),
        migrations.AddField(
            model_name='cruisetour',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否啟用'),
        ),
        migrations.AddField(
            model_name='cruisetour',
            name='title_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='標題 (簡體)'),
        ),
        migrations.AddField(
            model_name='cruisetour',
            name='title_zh_hant',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='標題 (繁體)'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_zh_hans',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='地區名稱 (簡體)'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_zh_hant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='地區名稱 (繁體)'),
        ),
        migrations.AlterField(
            model_name='cruisetour',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cruisetour',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='標題 (英文)'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='地區名稱 (英文)'),
        ),
        migrations.CreateModel(
            name='CruisePort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_zh_hant', models.CharField(blank=True, max_length=100, null=True, verbose_name='港口名稱 (繁體)')),
                ('name_zh_hans', models.CharField(blank=True, max_length=100, null=True, verbose_name='港口名稱 (簡體)')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='港口名稱 (英文)')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='cruise.region')),
            ],
        ),
        migrations.AddField(
            model_name='cruisetour',
            name='departure_port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours', to='cruise.cruiseport'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='CruiseLine',
        ),
        migrations.DeleteModel(
            name='CruiseShip',
        ),
    ]
