# Generated by Django 5.2.6 on 2025-09-21 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruise', '0005_remove_cruisetour_city_remove_cruisetour_cruise_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruisetour',
            name='departure_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cruise.region', verbose_name='出發地區'),
        ),
        migrations.AlterField(
            model_name='cruiseport',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Port Name (EN)'),
        ),
        migrations.AlterField(
            model_name='cruiseport',
            name='name_zh_hans',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='港口名称 (简体)'),
        ),
        migrations.AlterField(
            model_name='cruisetour',
            name='departure_port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cruise.cruiseport', verbose_name='出發港口'),
        ),
        migrations.AlterField(
            model_name='cruisetour',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description (EN)'),
        ),
        migrations.AlterField(
            model_name='cruisetour',
            name='description_zh_hans',
            field=models.TextField(blank=True, null=True, verbose_name='描述 (简体)'),
        ),
        migrations.AlterField(
            model_name='cruisetour',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='價格'),
        ),
        migrations.AlterField(
            model_name='cruisetour',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (EN)'),
        ),
        migrations.AlterField(
            model_name='cruisetour',
            name='title_zh_hans',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='标题 (简体)'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Region Name (EN)'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name_zh_hans',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='地区名称 (简体)'),
        ),
    ]
